/* ============================================================
   SEO AUDIT CHECKLIST — DATA
   All step definitions, sub-tasks, and tool references.
   Edit this file to customise steps, tasks, tips, and tools.
   ============================================================ */

const STEP_COLORS = [
  '#f5735a', // Step 1 — coral
  '#4aaaf0', // Step 2 — blue
  '#6fde8e', // Step 3 — green
  '#f0c34a', // Step 4 — amber
  '#c97af5', // Step 5 — purple
  '#4af0c3', // Step 6 — teal
  '#f57ac9', // Step 7 — pink
  '#a0a09a', // Step 8 — slate
];

/* ----------------------------------------------------------------
   METRIC LABEL SETS
   Each score card cycles through these label variants over time.
   Edit or add labels — they rotate on a staggered interval.
   ---------------------------------------------------------------- */
const METRIC_LABELS = {
  steps: [
    'Steps complete',
    'Steps finished',
    'Phases done',
    'Stages cleared',
    'Milestones hit',
  ],
  tasks: [
    'Tasks done',
    'Items checked',
    'Actions taken',
    'Tasks complete',
    'Checks passed',
  ],
  remaining: [
    'Still to do',
    'Left to action',
    'Pending tasks',
    'Outstanding',
    'Items remaining',
  ],
  score: [
    'Audit score',
    'Completion %',
    'Overall health',
    'Progress score',
    'SEO readiness',
  ],
};

/* ----------------------------------------------------------------
   STEPS DATA
   Each step has:
    - id        unique string
    - num       display number (1–8)
    - title     short title shown in header
    - tools     array of tool names shown as tags
    - tip       expanded tip shown inside the step body
    - subs      array of sub-tasks { id, label, desc }
   ---------------------------------------------------------------- */
const STEPS = [
  {
    id: 's1',
    num: 1,
    title: 'Check obvious errors with a crawl',
    tools: ['Screaming Frog'],
    tip: 'Run a full crawl of your site. Export the results and filter by status codes — fix all 4xx errors first, then 3xx redirect chains. For sites over 500 pages, use the free version in list mode.',
    subs: [
      {
        id: 's1a',
        label: 'Run a full site crawl',
        desc: 'Set Screaming Frog to crawl all pages — allow sufficient time for large sites. Check Configuration → Spider settings first.',
      },
      {
        id: 's1b',
        label: 'Identify & fix 404 broken links',
        desc: 'Export URLs with 4xx status codes. Redirect broken internal links to the closest relevant page using 301 redirects.',
      },
      {
        id: 's1c',
        label: 'Resolve redirect chains & loops',
        desc: 'Flag any 301/302 chains longer than 1 hop and streamline them to a single direct redirect to avoid crawl budget waste.',
      },
      {
        id: 's1d',
        label: 'Find and fix duplicate page titles/descriptions',
        desc: 'Export the Title and Meta Description columns in Screaming Frog, filter for duplicates, and update each page.',
      },
      {
        id: 's1e',
        label: 'Flag pages blocked by robots.txt or noindex',
        desc: 'Cross-check crawl data with intended indexing — unblock any pages incorrectly excluded from Googlebot.',
      },
    ],
  },
  {
    id: 's2',
    num: 2,
    title: 'Check metadata',
    tools: ['SEO Meta in 1 Click'],
    tip: 'Install the browser extension and use it to instantly review title tags, meta descriptions, and canonical tags on any live page without needing to open the source code.',
    subs: [
      {
        id: 's2a',
        label: 'Review title tags on all key pages',
        desc: 'Title tags should be 50–60 characters, include the primary keyword near the front, and be unique per page.',
      },
      {
        id: 's2b',
        label: 'Check meta descriptions are present',
        desc: '150–160 characters, compelling, and include a soft CTA. Missing ones get auto-generated by Google — usually poorly.',
      },
      {
        id: 's2c',
        label: 'Verify canonical tags are correct',
        desc: 'Each page should self-canonicalise or point to the correct preferred URL to prevent duplicate content signals.',
      },
      {
        id: 's2d',
        label: 'Check Open Graph / Twitter Card tags',
        desc: 'OG title, description, and image should be set correctly for social sharing previews across all key landing pages.',
      },
    ],
  },
  {
    id: 's3',
    num: 3,
    title: 'Check H tags and missing alt text',
    tools: ['Screaming Frog', 'ChatGPT'],
    tip: 'Export H1/H2 data from Screaming Frog, then paste the list into ChatGPT and ask it to flag missing, duplicate, or keyword-weak headings. It\'s surprisingly fast at this.',
    subs: [
      {
        id: 's3a',
        label: 'Ensure every page has exactly one H1',
        desc: 'Multiple or missing H1s are a common crawl finding. Fix all pages with 0 or more than 1 H1 tag.',
      },
      {
        id: 's3b',
        label: 'Check H2–H4 hierarchy is logical',
        desc: 'Headings should outline the page content clearly — avoid skipping levels (e.g. H1 → H3 with no H2).',
      },
      {
        id: 's3c',
        label: 'Add missing alt text to all images',
        desc: 'Export images with blank alt text from Screaming Frog and write descriptive (not keyword-stuffed) alt copy for each.',
      },
      {
        id: 's3d',
        label: 'Use ChatGPT to rewrite weak headings',
        desc: 'Paste headings into ChatGPT and prompt: "Rewrite these H tags to be more keyword-rich while staying natural and readable."',
      },
      {
        id: 's3e',
        label: 'Confirm primary keyword appears in H1',
        desc: 'The primary keyword should appear in the H1 naturally — avoid forcing it awkwardly just to include it.',
      },
    ],
  },
  {
    id: 's4',
    num: 4,
    title: 'Optimise images and compress files',
    tools: ['TinyPNG'],
    tip: 'Unoptimised images are one of the biggest page speed culprits. Compress all images before uploading — aim for under 150KB per image where possible. WebP format gives 25–35% better compression than JPEG.',
    subs: [
      {
        id: 's4a',
        label: 'Compress all images via TinyPNG',
        desc: 'Drag and drop PNG and JPEG files — typically 50–80% file size reduction with no visible quality loss.',
      },
      {
        id: 's4b',
        label: 'Convert images to WebP format',
        desc: 'WebP is significantly smaller than JPEG/PNG. Use for all new uploads and batch convert existing images where supported.',
      },
      {
        id: 's4c',
        label: 'Set explicit width & height on image tags',
        desc: 'Prevents Cumulative Layout Shift (CLS) — a Core Web Vitals factor that affects both UX and rankings.',
      },
      {
        id: 's4d',
        label: 'Implement lazy loading for below-fold images',
        desc: 'Add loading="lazy" to all images not visible on initial page load to defer non-critical resource fetching.',
      },
    ],
  },
  {
    id: 's5',
    num: 5,
    title: 'Check page speed and load times',
    tools: ['GTmetrix', 'Pingdom Tools'],
    tip: 'Test from multiple server locations using both tools. GTmetrix gives Lighthouse-based performance scores; Pingdom shows waterfall breakdowns to pinpoint exactly which assets are slow.',
    subs: [
      {
        id: 's5a',
        label: 'Run GTmetrix on key pages',
        desc: 'Target Grade A (90+ performance score). Export the report and action the top recommendations first.',
      },
      {
        id: 's5b',
        label: 'Run Pingdom speed test',
        desc: 'Test from the server location nearest to your audience — aim for under 3 seconds total load time.',
      },
      {
        id: 's5c',
        label: 'Pass Core Web Vitals (LCP, FID, CLS)',
        desc: 'LCP < 2.5s, FID < 100ms, CLS < 0.1 — check via the Core Web Vitals report in Google Search Console.',
      },
      {
        id: 's5d',
        label: 'Enable browser caching on static assets',
        desc: 'Static assets (images, CSS, JS) should have cache headers set for at least 1 year to avoid repeat downloads.',
      },
      {
        id: 's5e',
        label: 'Minify CSS, JavaScript, and HTML',
        desc: 'Use a plugin (WP Rocket, NitroPack) or manual minification to strip whitespace and reduce file sizes.',
      },
      {
        id: 's5f',
        label: 'Enable GZIP or Brotli compression on server',
        desc: 'Server-level compression reduces transfer size of text-based assets by around 70% — check via GTmetrix recommendations.',
      },
    ],
  },
  {
    id: 's6',
    num: 6,
    title: 'Check sitemap and indexing setup',
    tools: ['Google Search Console'],
    tip: 'Google Search Console is your most direct window into how Google sees your site. Submit your sitemap, then review the Coverage report — check it at least weekly for new errors.',
    subs: [
      {
        id: 's6a',
        label: 'Submit XML sitemap to Google Search Console',
        desc: 'Go to Settings → Sitemaps → add your sitemap URL (usually /sitemap.xml or /sitemap_index.xml).',
      },
      {
        id: 's6b',
        label: 'Review Coverage report for index errors',
        desc: 'Examine Excluded, Error, and Warning pages — make a decision on each: fix it, redirect it, or intentionally exclude it.',
      },
      {
        id: 's6c',
        label: 'Confirm HTTPS version is the canonical version',
        desc: 'Verify GSC is set to the HTTPS preferred domain — www or non-www — and that HTTP redirects to it.',
      },
      {
        id: 's6d',
        label: 'Use URL Inspection for key landing pages',
        desc: 'Inspect your top pages to confirm they are indexed, rendering correctly, and not blocked by noindex or robots.',
      },
      {
        id: 's6e',
        label: 'Request indexing for updated pages',
        desc: 'After significant content changes, use URL Inspection → Request Indexing to prompt a fast recrawl.',
      },
    ],
  },
  {
    id: 's7',
    num: 7,
    title: 'Check CTR and improve clicks',
    tools: ['Google Search Console', 'ChatGPT'],
    tip: 'Export queries with high impressions but low CTR from GSC — these are your quickest wins. Pages ranking in positions 1–10 with under 3% CTR have weak titles or descriptions. Use ChatGPT to rewrite them.',
    subs: [
      {
        id: 's7a',
        label: 'Export GSC performance data by query',
        desc: 'Filter by last 3 months, sort by Impressions descending — identify high-impression, low-CTR queries.',
      },
      {
        id: 's7b',
        label: 'Identify pages with CTR below 3%',
        desc: 'Pages ranking in positions 1–10 but below 3% CTR are priority targets for title and description rewrites.',
      },
      {
        id: 's7c',
        label: 'Use ChatGPT to rewrite low-CTR title tags',
        desc: 'Prompt: "Rewrite this title tag to be more click-worthy for someone searching [query]: [current title]."',
      },
      {
        id: 's7d',
        label: 'Monitor CTR improvement over 4–6 weeks',
        desc: 'Apply rewritten titles then track weekly in GSC — compare CTR before/after for each updated page.',
      },
      {
        id: 's7e',
        label: 'Check average position for target keywords',
        desc: 'Keywords in positions 4–10 are candidates for content improvement — adding depth, FAQs, or schema can push them higher.',
      },
    ],
  },
  {
    id: 's8',
    num: 8,
    title: 'Use ChatGPT (paid) to fix SEO issues faster',
    tools: ['ChatGPT Plus'],
    tip: 'ChatGPT (paid) with web browsing and code interpreter dramatically speeds up bulk tasks. Think of it as your SEO analyst — feed it raw exports from Screaming Frog or GSC and ask it to prioritise issues.',
    subs: [
      {
        id: 's8a',
        label: 'Bulk-generate missing meta descriptions',
        desc: 'Export pages with missing descriptions, paste into ChatGPT, and generate all of them in a single prompt with clear formatting.',
      },
      {
        id: 's8b',
        label: 'Rewrite duplicate or thin page titles',
        desc: 'Feed in your list of duplicate titles — ask ChatGPT to make each unique based on the page topic and keyword.',
      },
      {
        id: 's8c',
        label: 'Generate alt text for images in bulk',
        desc: 'Share image filenames or a list of URLs and ask ChatGPT to suggest descriptive, natural alt text for each one.',
      },
      {
        id: 's8d',
        label: 'Paste crawl exports for prioritised recommendations',
        desc: 'Paste Screaming Frog CSV exports and ask: "What are the top 5 issues I should fix first based on SEO impact?"',
      },
      {
        id: 's8e',
        label: 'Produce optimised content outlines',
        desc: 'Ask ChatGPT to create keyword-rich content outlines based on your target queries, search intent, and competitor gaps.',
      },
    ],
  },
];
