/* ============================================================
   data-store.js
   Central reference schemas and default templates for all tools.
   ============================================================ */

// 1. DEFAULT ONBOARDING CHECKLIST
const DEFAULT_ONBOARDING_CHECKLIST = [
  {
    category: 'Pre-Onboarding (Internal Prep)',
    items: [
      { id: 'ob_pre1', label: 'Review signed contract, proposal, and Statement of Work (SOW)' },
      { id: 'ob_pre2', label: 'Assign dedicated account manager and team members' },
      { id: 'ob_pre3', label: 'Set up internal project folder structure (Admin, Brief, Assets, Working, Deliverables)' },
      { id: 'ob_pre4', label: 'Create CRM entry and configure project management board (Asana/Monday/ClickUp)' }
    ]
  },
  {
    category: 'Administrative & Technical Setup',
    items: [
      { id: 'ob_admin1', label: 'Send welcome package with timelines, team roles, and communication protocols' },
      { id: 'ob_admin2', label: 'Collect signed agreements, NDAs, and process initial invoices' },
      { id: 'ob_admin3', label: 'Gather access credentials (GA4, Google Ads, CMS, Social accounts, etc.)' }
    ]
  },
  {
    category: 'Discovery & Kickoff',
    items: [
      { id: 'ob_kick1', label: 'Send intake questionnaire (covering goals, brand guidelines, competitors)' },
      { id: 'ob_kick2', label: 'Schedule and conduct internal prep meeting before client kickoff' },
      { id: 'ob_kick3', label: 'Conduct official client kickoff meeting with a pre-shared agenda' },
      { id: 'ob_kick4', label: 'Define final success metrics (KPIs), reporting frequency, and first deliverables' }
    ]
  }
];

// 2. DEFAULT SEO AUDIT (8 Steps from reference)
const DEFAULT_SEO_AUDIT = [
  {
    id: 's1',
    num: 1,
    title: 'Check obvious errors with a crawl',
    tools: ['Screaming Frog'],
    tip: 'Run a full crawl of your site. Export the results and filter by status codes — fix all 4xx errors first, then 3xx redirect chains. For sites over 500 pages, use the free version in list mode.',
    subs: [
      { id: 's1a', label: 'Run a full site crawl', desc: 'Set Screaming Frog to crawl all pages — allow sufficient time for large sites. Check Configuration → Spider settings first.' },
      { id: 's1b', label: 'Identify & fix 404 broken links', desc: 'Export URLs with 4xx status codes. Redirect broken internal links to the closest relevant page using 301 redirects.' },
      { id: 's1c', label: 'Resolve redirect chains & loops', desc: 'Flag any 301/302 chains longer than 1 hop and streamline them to a single direct redirect to avoid crawl budget waste.' },
      { id: 's1d', label: 'Find and fix duplicate page titles/descriptions', desc: 'Export the Title and Meta Description columns in Screaming Frog, filter for duplicates, and update each page.' },
      { id: 's1e', label: 'Flag pages blocked by robots.txt or noindex', desc: 'Cross-check crawl data with intended indexing — unblock any pages incorrectly excluded from Googlebot.' }
    ]
  },
  {
    id: 's2',
    num: 2,
    title: 'Check metadata',
    tools: ['SEO Meta in 1 Click'],
    tip: 'Install the browser extension and use it to instantly review title tags, meta descriptions, and canonical tags on any live page without needing to open the source code.',
    subs: [
      { id: 's2a', label: 'Review title tags on all key pages', desc: 'Title tags should be 50–60 characters, include the primary keyword near the front, and be unique per page.' },
      { id: 's2b', label: 'Check meta descriptions are present', desc: '150–160 characters, compelling, and include a soft CTA. Missing ones get auto-generated by Google — usually poorly.' },
      { id: 's2c', label: 'Verify canonical tags are correct', desc: 'Each page should self-canonicalise or point to the correct preferred URL to prevent duplicate content signals.' },
      { id: 's2d', label: 'Check Open Graph / Twitter Card tags', desc: 'OG title, description, and image should be set correctly for social sharing previews across all key landing pages.' }
    ]
  },
  {
    id: 's3',
    num: 3,
    title: 'Check H tags and missing alt text',
    tools: ['Screaming Frog', 'ChatGPT'],
    tip: 'Export H1/H2 data from Screaming Frog, then paste the list into ChatGPT and ask it to flag missing, duplicate, or keyword-weak headings. It\'s surprisingly fast at this.',
    subs: [
      { id: 's3a', label: 'Ensure every page has exactly one H1', desc: 'Multiple or missing H1s are a common crawl finding. Fix all pages with 0 or more than 1 H1 tag.' },
      { id: 's3b', label: 'Check H2–H4 hierarchy is logical', desc: 'Headings should outline the page content clearly — avoid skipping levels (e.g. H1 → H3 with no H2).' },
      { id: 's3c', label: 'Add missing alt text to all images', desc: 'Export images with blank alt text from Screaming Frog and write descriptive (not keyword-stuffed) alt copy for each.' },
      { id: 's3d', label: 'Use ChatGPT to rewrite weak headings', desc: 'Paste headings into ChatGPT and prompt: "Rewrite these H tags to be more keyword-rich while staying natural and readable."' },
      { id: 's3e', label: 'Confirm primary keyword appears in H1', desc: 'The primary keyword should appear in the H1 naturally — avoid forcing it awkwardly just to include it.' }
    ]
  },
  {
    id: 's4',
    num: 4,
    title: 'Optimise images and compress files',
    tools: ['TinyPNG'],
    tip: 'Unoptimised images are one of the biggest page speed culprits. Compress all images before uploading — aim for under 150KB per image where possible. WebP format gives 25–35% better compression than JPEG.',
    subs: [
      { id: 's4a', label: 'Compress all images via TinyPNG', desc: 'Drag and drop PNG and JPEG files — typically 50–80% file size reduction with no visible quality loss.' },
      { id: 's4b', label: 'Convert images to WebP format', desc: 'WebP is significantly smaller than JPEG/PNG. Use for all new uploads and batch convert existing images where supported.' },
      { id: 's4c', label: 'Set explicit width & height on image tags', desc: 'Prevents Cumulative Layout Shift (CLS) — a Core Web Vitals factor that affects both UX and rankings.' },
      { id: 's4d', label: 'Implement lazy loading for below-fold images', desc: 'Add loading="lazy" to all images not visible on initial page load to defer non-critical resource fetching.' }
    ]
  },
  {
    id: 's5',
    num: 5,
    title: 'Check page speed and load times',
    tools: ['GTmetrix', 'Pingdom Tools'],
    tip: 'Test from multiple server locations using both tools. GTmetrix gives Lighthouse-based performance scores; Pingdom shows waterfall breakdowns to pinpoint exactly which assets are slow.',
    subs: [
      { id: 's5a', label: 'Run GTmetrix on key pages', desc: 'Target Grade A (90+ performance score). Export the report and action the top recommendations first.' },
      { id: 's5b', label: 'Run Pingdom speed test', desc: 'Test from the server location nearest to your audience — aim for under 3 seconds total load time.' },
      { id: 's5c', label: 'Pass Core Web Vitals (LCP, FID, CLS)', desc: 'LCP < 2.5s, FID < 100ms, CLS < 0.1 — check via the Core Web Vitals report in Google Search Console.' },
      { id: 's5d', label: 'Enable browser caching on static assets', desc: 'Static assets (images, CSS, JS) should have cache headers set for at least 1 year to avoid repeat downloads.' },
      { id: 's5e', label: 'Minify CSS, JavaScript, and HTML', desc: 'Use a plugin (WP Rocket, NitroPack) or manual minification to strip whitespace and reduce file sizes.' },
      { id: 's5f', label: 'Enable GZIP or Brotli compression on server', desc: 'Server-level compression reduces transfer size of text-based assets by around 70% — check via GTmetrix recommendations.' }
    ]
  },
  {
    id: 's6',
    num: 6,
    title: 'Check sitemap and indexing setup',
    tools: ['Google Search Console'],
    tip: 'Google Search Console is your most direct window into how Google sees your site. Submit your sitemap, then review the Coverage report — check it at least weekly for new errors.',
    subs: [
      { id: 's6a', label: 'Submit XML sitemap to Google Search Console', desc: 'Go to Settings → Sitemaps → add your sitemap URL (usually /sitemap.xml or /sitemap_index.xml).' },
      { id: 's6b', label: 'Review Coverage report for index errors', desc: 'Examine Excluded, Error, and Warning pages — make a decision on each: fix it, redirect it, or intentionally exclude it.' },
      { id: 's6c', label: 'Confirm HTTPS version is the canonical version', desc: 'Verify GSC is set to the HTTPS preferred domain — www or non-www — and that HTTP redirects to it.' },
      { id: 's6d', label: 'Use URL Inspection for key landing pages', desc: 'Inspect your top pages to confirm they are indexed, rendering correctly, and not blocked by noindex or robots.' },
      { id: 's6e', label: 'Request indexing for updated pages', desc: 'After significant content changes, use URL Inspection → Request Indexing to prompt a fast recrawl.' }
    ]
  },
  {
    id: 's7',
    num: 7,
    title: 'Check CTR and improve clicks',
    tools: ['Google Search Console', 'ChatGPT'],
    tip: 'Export queries with high impressions but low CTR from GSC — these are your quickest wins. Pages ranking in positions 1–10 with under 3% CTR have weak titles or descriptions. Use ChatGPT to rewrite them.',
    subs: [
      { id: 's7a', label: 'Export GSC performance data by query', desc: 'Filter by last 3 months, sort by Impressions descending — identify high-impression, low-CTR queries.' },
      { id: 's7b', label: 'Identify pages with CTR below 3%', desc: 'Pages ranking in positions 1–10 but below 3% CTR are priority targets for title and description rewrites.' },
      { id: 's7c', label: 'Use ChatGPT to rewrite low-CTR title tags', desc: 'Prompt: "Rewrite this title tag to be more click-worthy for someone searching [query]: [current title]."' },
      { id: 's7d', label: 'Monitor CTR improvement over 4–6 weeks', desc: 'Apply rewritten titles then track weekly in GSC — compare CTR before/after for each updated page.' },
      { id: 's7e', label: 'Check average position for target keywords', desc: 'Keywords in positions 4–10 are candidates for content improvement — adding depth, FAQs, or schema can push them higher.' }
    ]
  },
  {
    id: 's8',
    num: 8,
    title: 'Use ChatGPT (paid) to fix SEO issues faster',
    tools: ['ChatGPT Plus'],
    tip: 'ChatGPT (paid) with web browsing and code interpreter dramatically speeds up bulk tasks. Think of it as your SEO analyst — feed it raw exports from Screaming Frog or GSC and ask it to prioritise issues.',
    subs: [
      { id: 's8a', label: 'Bulk-generate missing meta descriptions', desc: 'Export pages with missing descriptions, paste into ChatGPT, and generate all of them in a single prompt with clear formatting.' },
      { id: 's8b', label: 'Rewrite duplicate or thin page titles', desc: 'Feed in your list of duplicate titles — ask ChatGPT to make each unique based on the page topic and keyword.' },
      { id: 's8c', label: 'Generate alt text for images in bulk', desc: 'Share image filenames or a list of URLs and ask ChatGPT to suggest descriptive, natural alt text for each one.' },
      { id: 's8d', label: 'Paste crawl exports for prioritised recommendations', desc: 'Paste Screaming Frog CSV exports and ask: "What are the top 5 issues I should fix first based on SEO impact?"' },
      { id: 's8e', label: 'Produce optimised content outlines', desc: 'Ask ChatGPT to create keyword-rich content outlines based on your target queries, search intent, and competitor gaps.' }
    ]
  }
];

// 3. UX/UI AUDIT CRITERIA
const DEFAULT_UXUI_AUDIT = [
  {
    id: 'u1',
    category: 'Navigation & Structure',
    rating: 5,
    notes: '',
    items: [
      { id: 'u1a', label: 'Consistent and clear primary menu hierarchy.' },
      { id: 'u1b', label: 'Sticky header present for long pages.' },
      { id: 'u1c', label: 'Footer has descriptive contact, legal, and sitemap links.' },
      { id: 'u1d', label: 'Search feature or site index is working and helpful.' }
    ]
  },
  {
    id: 'u2',
    category: 'Visual Design & Spacing',
    rating: 5,
    notes: '',
    items: [
      { id: 'u2a', label: 'Readable font sizes, line heights, and typography hierarchy.' },
      { id: 'u2b', label: 'Consistent spacing patterns (vertical and horizontal grids).' },
      { id: 'u2c', label: 'High color contrast for readability (WCAG AA compliant).' },
      { id: 'u2d', label: 'Branding aesthetic matches the audience\'s expectations.' }
    ]
  },
  {
    id: 'u3',
    category: 'Forms & Interactions',
    rating: 5,
    notes: '',
    items: [
      { id: 'u3a', label: 'Forms require minimal fields and have inline validation.' },
      { id: 'u3b', label: 'Clear feedback or transition states on hover/focus.' },
      { id: 'u3c', label: 'Success states are visible, clean, and provide clear next steps.' },
      { id: 'u3d', label: 'Errors are helpful rather than generic blocks of red text.' }
    ]
  },
  {
    id: 'u4',
    category: 'Conversion & CTAs',
    rating: 5,
    notes: '',
    items: [
      { id: 'u4a', label: 'Primary Call-To-Action (CTA) is highly visible above the fold.' },
      { id: 'u4b', label: 'Supporting CTAs offer softer conversions (e.g. newsletter, guides).' },
      { id: 'u4c', label: 'Value proposition is clear and easy to grasp within 5 seconds.' },
      { id: 'u4d', label: 'No distracting popups or sliders competing with primary goals.' }
    ]
  },
  {
    id: 'u5',
    category: 'Mobile Responsiveness',
    rating: 5,
    notes: '',
    items: [
      { id: 'u5a', label: 'Menus fold into a clean hamburger/overlay on small screens.' },
      { id: 'u5b', label: 'Tap targets (buttons/links) are at least 48x48px with plenty of margin.' },
      { id: 'u5c', label: 'No horizontal overflow or broken image/table wrappers.' },
      { id: 'u5d', label: 'Fast page transition times and layout stability (no shifts).' }
    ]
  }
];

// 4. WEBSITE COMPETITOR AUDIT CONFIG
const WEBSITE_COMPETITOR_ROWS = [
  { key: 'val_prop', label: 'Primary Value Prop', placeholder: 'e.g. Messaging clarity, core hook...' },
  { key: 'design_ux', label: 'Design & UX Quality', placeholder: 'e.g. Modern, clean, typography...' },
  { key: 'mobile_ux', label: 'Mobile Responsive UX', placeholder: 'e.g. Navigation, scaling, tap-friendly...' },
  { key: 'features', label: 'Key Site Features', placeholder: 'e.g. Booking, portal, blog, search...' },
  { key: 'cta_funnel', label: 'Primary CTA & Funnel', placeholder: 'e.g. Inquire button, lead magnet...' },
  { key: 'seo_kw', label: 'SEO & Organic Keywords', placeholder: 'e.g. Ranks #1 for "X production", backlinks...' },
  { key: 'speed_perf', label: 'Load Speed & Perf', placeholder: 'e.g. Lighthouse score, desktop vs mobile...' },
  { key: 'tech_stack', label: 'Technology Stack', placeholder: 'e.g. Webflow, WordPress, Shopify...' },
  { key: 'social_proof', label: 'Social Proof & Trust', placeholder: 'e.g. Testimonials, logos, case studies...' },
  { key: 'nav_struct', label: 'Navigation & Structure', placeholder: 'e.g. Simple, intuitive menu, internal links...' }
];

const WEBSITE_SWOT_PROMPTS = [
  {
    key: 's',
    label: 'Strengths',
    sub: 'You vs. them',
    borderColor: '#10b981',
    placeholder: 'What does your website do better? Clearer value prop, faster speed, better conversion...',
    prompts: [
      'Our website loads significantly faster than competitors because ___',
      'Our primary value proposition is clearer above the fold: ___',
      'We offer an interactive tool/calculator that they lack: ___',
      'Our responsive layout and mobile menu are more intuitive',
      'We showcase stronger client video testimonials and social proof',
      'Our contact form is shorter and easier to fill out',
      'Our website branding is more modern and premium than theirs',
      'We have a dedicated client portal that increases retention'
    ]
  },
  {
    key: 'w',
    label: 'Weaknesses',
    sub: 'To address',
    borderColor: '#ef4444',
    placeholder: 'Where do competitor websites outperform yours? Domain authority, resources...',
    prompts: [
      'Our website load time on mobile is slow, causing bounces',
      'We lack clear navigation and visitors get lost looking for ___',
      'Competitors rank higher for main industry keywords because ___',
      'Our typography and color styling feel outdated',
      'We do not have a resource/blog section to attract top-of-funnel traffic',
      'Our website does not make it easy to book a call directly',
      'We do not display client logos or reviews on the homepage',
      'Our website copy is too long and complex for quick reading'
    ]
  },
  {
    key: 'o',
    label: 'Opportunities',
    sub: 'Market gaps',
    borderColor: '#3b82f6',
    placeholder: 'Feature gaps, SEO keywords, emerging design layouts...',
    prompts: [
      'We can target local keywords that competitors are ignoring, e.g. ___',
      'None of the competitors have a self-serve booking calendar',
      'We can add a dynamic FAQ section matching recent search trends',
      'Adding video background headers can set us apart visually',
      'We can launch a high-value lead magnet (e.g. guide or audit tool)',
      'No competitor explains their production process visually; we can do this',
      'We can build a resource center to capture educational searches',
      'Improving our Google Lighthouse score can boost our ranking'
    ]
  },
  {
    key: 't',
    label: 'Threats',
    sub: 'To watch',
    borderColor: '#ec4899',
    placeholder: 'Competitor redesigns, search trends, AI search impact...',
    prompts: [
      '___ competitor just launched a fully custom modern redesign',
      'Competitors have very high Domain Authority, making SEO hard to beat',
      'Search engines are using AI overviews, reducing organic traffic to blog links',
      'Competitors are running paid search ads for our primary services',
      'They have automated chatbot workflows that capture leads instantly',
      'Their website has translated versions, capturing international clients',
      'Algorithm updates might penalize sites with our current stack',
      'Competitors are offering free tools/checklists that dominate search traffic'
    ]
  }
];

// 5. SOCIAL MEDIA COMPETITOR AUDIT CONFIG
const SOCIAL_COMPETITOR_ROWS = [
  { key: 'followers', label: 'Followers', placeholder: 'e.g. 120K IG, 45K TT' },
  { key: 'frequency', label: 'Posting Frequency', placeholder: 'e.g. Daily reels, 3x/week' },
  { key: 'style', label: 'Content Style', placeholder: 'Cinematic, UGC, editorial…' },
  { key: 'engagement', label: 'Engagement Rate', placeholder: 'e.g. ~3.2% avg' },
  { key: 'views', label: 'Avg Video Views', placeholder: 'e.g. 50K per reel' },
  { key: 'best_content', label: 'Best Performing Content', placeholder: 'BTS, client results, trends…' },
  { key: 'pricing', label: 'Pricing Model', placeholder: 'Retainer / project / hourly' },
  { key: 'identity', label: 'Brand Identity', placeholder: 'Tone, aesthetic, positioning…' },
  { key: 'clients', label: 'Target Clients', placeholder: 'SMBs, lifestyle brands…' }
];

const SOCIAL_SWOT_PROMPTS = [
  {
    key: 's',
    label: 'Strengths',
    sub: 'You vs. them',
    borderColor: '#10b981',
    placeholder: 'What do you do better? Full-service team, faster turnaround, stronger storytelling…',
    prompts: [
      'We turn projects around faster than competitors because ___',
      'Our content quality stands out because ___',
      'We offer something competitors don\'t: ___',
      'Clients choose us over others because ___',
      'Our team\'s unique skill or background is ___',
      'We have stronger relationships in ___ industry/niche',
      'Our pricing is more competitive because ___',
      'We\'re better at storytelling / brand voice because ___'
    ]
  },
  {
    key: 'w',
    label: 'Weaknesses',
    sub: 'To address',
    borderColor: '#ef4444',
    placeholder: 'Where do competitors outperform you? Brand recognition, niche expertise…',
    prompts: [
      'We lack brand recognition in ___ market',
      'Competitors have a larger following on ___',
      'We don\'t yet offer ___ as a service',
      'Our content on ___ platform is underdeveloped',
      'We lose clients to competitors on price because ___',
      'Our team is missing expertise in ___',
      'We don\'t have enough case studies or social proof in ___',
      'Our onboarding / client process needs work in ___'
    ]
  },
  {
    key: 'o',
    label: 'Opportunities',
    sub: 'Market gaps',
    borderColor: '#3b82f6',
    placeholder: 'Underserved niches, emerging platforms, verticals they ignore…',
    prompts: [
      'No competitor is strongly serving ___ type of client',
      '___ platform is growing but competitors aren\'t on it yet',
      'There\'s demand for ___ style of content nobody does well',
      'We could white-label or partner with ___',
      '___ industry is underserved for content production',
      'Brands are moving from ___ toward ___ — we can lead that',
      'There\'s a gap in ___ price range we could own',
      'A trend we can capitalize on before competitors: ___'
    ]
  },
  {
    key: 't',
    label: 'Threats',
    sub: 'To watch',
    borderColor: '#ec4899',
    placeholder: 'Competitor pivots, pricing pressure, AI tools, algorithm shifts…',
    prompts: [
      '___ competitor is growing fast targeting our same clients',
      'AI tools like ___ could undercut our pricing or workflow',
      '___ platform\'s algorithm change could hurt content reach',
      'Clients are cutting budgets in ___ area',
      'A new competitor just entered the market offering ___',
      'Trends are shifting away from ___ content we specialize in',
      'Talent / freelancer costs are rising in ___',
      'Clients are starting to bring ___ in-house instead'
    ]
  }
];

// 6. DEFAULT REPORT CONFIG
const DEFAULT_REPORT_METRICS = [
  { key: 'followers_total', label: 'Followers (Total)', placeholder: 'e.g. 150K' },
  { key: 'followers_new', label: 'Followers (New)', placeholder: 'e.g. +2.4K' },
  { key: 'impressions', label: 'Impressions', placeholder: 'e.g. 1.2M' },
  { key: 'engagement', label: 'Engagement Rate', placeholder: 'e.g. 4.8%' },
  { key: 'posted', label: 'Content Posted', placeholder: 'e.g. 12 videos, 8 posts' },
  { key: 'top_post', label: 'Top Performing Post', placeholder: 'e.g. BTS Video (250k views)' }
];

const DEFAULT_REPORT_PLATFORMS = [
  { name: 'Instagram', color: '#534ab7' },
  { name: 'TikTok', color: '#1d9e75' },
  { name: 'YouTube', color: '#d85a30' }
];

const DEFAULT_REPORT_WINS = 'Describe key achievements, highlights, and wins from this month. Click here to edit...';
